"""empty message

Revision ID: 7512f93e82a8
Revises: f2d0aa9b8619
Create Date: 2023-05-24 23:59:04.426565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7512f93e82a8'
down_revision = 'f2d0aa9b8619'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
